reader:
  name: standard
  rawdata_dir: yfcc/raw_data
  dataset_dir: test_mffm/yfcc/yfcc_sp_2000.hdf5
  num_kpt: 2000

matcher:
  layer_num: 9

evaluator:
  name: AUC
  rescale: 1600
  num_pair: 4000
  inlier_th: 0.005
  error_th: 1
